-- 预设50种常见矿物数据

USE mineral_identification;

-- 清空现有数据
DELETE FROM mineral_features;
DELETE FROM identification_records;
DELETE FROM minerals;
ALTER TABLE minerals AUTO_INCREMENT = 1;
ALTER TABLE mineral_features AUTO_INCREMENT = 1;
ALTER TABLE identification_records AUTO_INCREMENT = 1;

-- 插入矿物数据
INSERT INTO minerals (name, name_cn, chemical_formula, typical_location, image_url, description) VALUES
('Talc', '滑石', 'Mg₃Si₄O₁₀(OH)₂', '中国辽宁、山东；美国纽约', 'https://mineralseducationcoalition.org/wp-content/uploads/Minerals_Talc-600x600.jpg', '最软的矿物，常用于制作化妆品和滑石粉'),
('Gypsum', '石膏', 'CaSO₄·2H₂O', '中国湖北、湖南；墨西哥', 'https://mineralseducationcoalition.org/wp-content/uploads/Minerals_Gypsum-600x600.jpg', '白色或无色透明，用于建筑和医学'),
('Calcite', '方解石', 'CaCO₃', '中国广西、云南；冰岛', 'https://mineralseducationcoalition.org/wp-content/uploads/Minerals_Calcite-600x600.jpg', '常见的碳酸盐矿物，具有双折射现象'),
('Fluorite', '萤石', 'CaF₂', '中国内蒙古、浙江；美国肯塔基', 'https://mineralseducationcoalition.org/wp-content/uploads/Minerals_Fluorite-600x600.jpg', '多彩的矿物，常用于制作荧光灯'),
('Apatite', '磷灰石', 'Ca₅(PO₄)₃(F,Cl,OH)', '中国云南、贵州；俄罗斯', 'https://mineralseducationcoalition.org/wp-content/uploads/Minerals_Apatite-600x600.jpg', '牙齿和骨骼的主要成分，也是磷矿'),
('Orthoclase', '正长石', 'KAlSi₃O₈', '中国山东、河南；挪威', 'https://mineralseducationcoalition.org/wp-content/uploads/Minerals_Orthoclase-600x600.jpg', '花岗岩的主要成分，用于陶瓷制作'),
('Quartz', '石英', 'SiO₂', '世界各地广泛分布', 'https://mineralseducationcoalition.org/wp-content/uploads/Minerals_Quartz-600x600.jpg', '最常见的矿物，用于玻璃和电子工业'),
('Topaz', '黄玉', 'Al₂SiO₄(F,OH)₂', '巴西、斯里兰卡、美国科罗拉多', 'https://mineralseducationcoalition.org/wp-content/uploads/Minerals_Topaz-600x600.jpg', '贵宝石，颜色多样'),
('Corundum', '刚玉', 'Al₂O₃', '缅甸、泰国、澳大利亚', 'https://mineralseducationcoalition.org/wp-content/uploads/Minerals_Corundum-600x600.jpg', '最硬的氧化物，红宝石和蓝宝石都是刚玉'),
('Diamond', '金刚石', 'C', '南非、俄罗斯、澳大利亚', 'https://mineralseducationcoalition.org/wp-content/uploads/Minerals_Diamond-600x600.jpg', '最硬的天然矿物，用于珠宝和工业切割'),
('Hematite', '赤铁矿', 'Fe₂O₃', '中国辽宁、安徽；巴西', 'https://mineralseducationcoalition.org/wp-content/uploads/Minerals_Hematite-600x600.jpg', '主要铁矿石，红色条痕'),
('Magnetite', '磁铁矿', 'Fe₃O₄', '中国辽宁、山东；瑞典', 'https://mineralseducationcoalition.org/wp-content/uploads/Minerals_Magnetite-600x600.jpg', '具有磁性的铁矿'),
('Pyrite', '黄铁矿', 'FeS₂', '中国广东、云南；西班牙', 'https://mineralseducationcoalition.org/wp-content/uploads/Minerals_Pyrite-600x600.jpg', '愚人金，黄铜色，金属光泽'),
('Galena', '方铅矿', 'PbS', '中国湖南、云南；美国密苏里', 'https://mineralseducationcoalition.org/wp-content/uploads/Minerals_Galena-600x600.jpg', '主要铅矿，立方体解理'),
('Sphalerite', '闪锌矿', 'ZnS', '中国湖南、广东；加拿大', 'https://mineralseducationcoalition.org/wp-content/uploads/Minerals_Sphalerite-600x600.jpg', '主要锌矿，条痕黄白色'),
('Chalcopyrite', '黄铜矿', 'CuFeS₂', '中国江西、云南；智利', 'https://mineralseducationcoalition.org/wp-content/uploads/Minerals_Chalcopyrite-600x600.jpg', '主要铜矿，黄铜色'),
('Malachite', '孔雀石', 'Cu₂(CO₃)(OH)₂', '中国广东、云南；刚果', 'https://mineralseducationcoalition.org/wp-content/uploads/Minerals_Malachite-600x600.jpg', '绿色铜矿，条痕绿色'),
('Azurite', '蓝铜矿', 'Cu₃(CO₃)₂(OH)₂', '中国广东、云南；纳米比亚', 'https://mineralseducationcoalition.org/wp-content/uploads/Minerals_Azurite-600x600.jpg', '蓝色铜矿，条痕蓝色'),
('Cinnabar', '辰砂', 'HgS', '中国贵州、湖南；西班牙', 'https://mineralseducationcoalition.org/wp-content/uploads/Minerals_Cinnabar-600x600.jpg', '主要汞矿，鲜红色'),
('Realgar', '雄黄', 'AsS', '中国湖南、云南；美国内华达', 'https://mineralseducationcoalition.org/wp-content/uploads/Minerals_Realgar-600x600.jpg', '橙红色，用于中药'),
('Orpiment', '雌黄', 'As₂S₃', '中国湖南、云南；土耳其', 'https://mineralseducationcoalition.org/wp-content/uploads/Minerals_Orpiment-600x600.jpg', '黄色，与雄黄共生'),
('Graphite', '石墨', 'C', '中国黑龙江、山东；斯里兰卡', 'https://mineralseducationcoalition.org/wp-content/uploads/Minerals_Graphite-600x600.jpg', '铅笔芯原料，导电'),
('Sulfur', '硫磺', 'S', '中国台湾、四川；意大利西西里', 'https://mineralseducationcoalition.org/wp-content/uploads/Minerals_Sulfur-600x600.jpg', '黄色，用于化工'),
('Olivine', '橄榄石', '(Mg,Fe)₂SiO₄', '中国吉林、河北；美国夏威夷', 'https://mineralseducationcoalition.org/wp-content/uploads/Minerals_Olivine-600x600.jpg', '橄榄绿色，镁铁硅酸盐'),
('Garnet', '石榴子石', '(Mg,Fe,Mn,Ca)₃(Al,Fe,Cr)₂(SiO₄)₃', '中国新疆、福建；印度', 'https://mineralseducationcoalition.org/wp-content/uploads/Minerals_Garnet-600x600.jpg', '宝石矿物，颜色多样'),
('Kyanite', '蓝晶石', 'Al₂SiO₅', '中国山东、河北；美国纽约', 'https://mineralseducationcoalition.org/wp-content/uploads/Minerals_Kyanite-600x600.jpg', '蓝色，片状，不定硬度'),
('Sillimanite', '矽线石', 'Al₂SiO₅', '中国辽宁、山东；缅甸', 'https://mineralseducationcoalition.org/wp-content/uploads/Minerals_Sillimanite-600x600.jpg', '纤维状，白色至灰色'),
('Andalusite', '红柱石', 'Al₂SiO₅', '中国辽宁、河南；西班牙', 'https://mineralseducationcoalition.org/wp-content/uploads/Minerals_Andalusite-600x600.jpg', '红褐色，方形截面'),
('Staurolite', '十字石', 'Fe₂Al₉Si₄O₂₃(OH)', '中国四川、西藏；瑞士', 'https://mineralseducationcoalition.org/wp-content/uploads/Minerals_Staurolite-600x600.jpg', '常呈十字形双晶'),
('Tourmaline', '电气石', 'Na(Li,Al)₃Al₆(BO₃)₃Si₆O₁₈(OH)₄', '巴西、马达加斯加、中国新疆', 'https://mineralseducationcoalition.org/wp-content/uploads/Minerals_Tourmaline-600x600.jpg', '颜色多样，压电效应'),
('Beryl', '绿柱石', 'Be₃Al₂Si₆O₁₈', '巴西、哥伦比亚、中国新疆', 'https://mineralseducationcoalition.org/wp-content/uploads/Minerals_Beryl-600x600.jpg', '含绿宝石和海蓝宝石'),
('Emerald', '祖母绿', 'Be₃Al₂Si₆O₁₈(Cr,V)', '哥伦比亚、巴西、赞比亚', 'https://mineralseducationcoalition.org/wp-content/uploads/Minerals_Emerald-600x600.jpg', '绿色绿柱石，贵宝石'),
('Aquamarine', '海蓝宝石', 'Be₃Al₂Si₆O₁₈(Fe²⁺)', '巴西、马达加斯加、中国新疆', 'https://mineralseducationcoalition.org/wp-content/uploads/Minerals_Aquamarine-600x600.jpg', '蓝色绿柱石'),
('Zircon', '锆石', 'ZrSiO₄', '泰国、斯里兰卡、中国内蒙古', 'https://mineralseducationcoalition.org/wp-content/uploads/Minerals_Zircon-600x600.jpg', '颜色多样，高折射率'),
('Spinel', '尖晶石', 'MgAl₂O₄', '缅甸、斯里兰卡、阿富汗', 'https://mineralseducationcoalition.org/wp-content/uploads/Minerals_Spinel-600x600.jpg', '常被误认为红宝石'),
('Chrysoberyl', '金绿宝石', 'BeAl₂O₄', '巴西、斯里兰卡、俄罗斯', 'https://mineralseducationcoalition.org/wp-content/uploads/Minerals_Chrysoberyl-600x600.jpg', '变石和猫眼石'),
('Peridot', '橄榄石宝石', '(Mg,Fe)₂SiO₄', '中国吉林、河北；巴基斯坦', 'https://mineralseducationcoalition.org/wp-content/uploads/Minerals_Peridot-600x600.jpg', '宝石级橄榄石'),
('Jadeite', '翡翠', 'NaAlSi₂O₆', '缅甸、危地马拉、日本', 'https://mineralseducationcoalition.org/wp-content/uploads/Minerals_Jadeite-600x600.jpg', '硬玉，珍贵玉石'),
('Nephrite', '软玉', 'Ca₂(Mg,Fe)₅Si₈O₂₂(OH)₂', '中国新疆、青海；加拿大', 'https://mineralseducationcoalition.org/wp-content/uploads/Minerals_Nephrite-600x600.jpg', '和田玉的主要成分'),
('Lapis Lazuli', '青金石', '(Na,Ca)₈(AlSiO₄)₆(S,SO₄,Cl)₁₋₂', '阿富汗、智利、俄罗斯', 'https://mineralseducationcoalition.org/wp-content/uploads/Minerals_Lapis_Lazuli-600x600.jpg', '深蓝色宝石，含黄铁矿'),
('Turquoise', '绿松石', 'CuAl₆(PO₄)₄(OH)₈·4H₂O', '中国湖北、新疆；伊朗', 'https://mineralseducationcoalition.org/wp-content/uploads/Minerals_Turquoise-600x600.jpg', '天蓝色，常用于珠宝'),
('Rhodochrosite', '菱锰矿', 'MnCO₃', '阿根廷、中国广西、美国科罗拉多', 'https://mineralseducationcoalition.org/wp-content/uploads/Minerals_Rhodochrosite-600x600.jpg', '粉红色，条痕白色'),
('Rhodonite', '蔷薇辉石', 'MnSiO₃', '中国辽宁、吉林；澳大利亚', 'https://mineralseducationcoalition.org/wp-content/uploads/Minerals_Rhodonite-600x600.jpg', '粉红色至红色'),
('Amazonite', '天河石', 'K(AlSi₃O₈)', '巴西、美国科罗拉多、俄罗斯', 'https://mineralseducationcoalition.org/wp-content/uploads/Minerals_Amazonite-600x600.jpg', '绿色微斜长石'),
('Labradorite', '拉长石', '(Ca,Na)(Al,Si)₄O₈', '加拿大拉布拉多、芬兰', 'https://mineralseducationcoalition.org/wp-content/uploads/Minerals_Labradorite-600x600.jpg', '变色效应，闪光'),
('Moonstone', '月光石', 'KAlSi₃O₈-NaAlSi₃O₈', '斯里兰卡、印度、缅甸', 'https://mineralseducationcoalition.org/wp-content/uploads/Minerals_Moonstone-600x600.jpg', '月光效应，长石'),
('Obsidian', '黑曜石', 'SiO₂(玻璃质)', '美国黄石、墨西哥、冰岛', 'https://mineralseducationcoalition.org/wp-content/uploads/Minerals_Obsidian-600x600.jpg', '火山玻璃，黑色'),
('Opal', '蛋白石', 'SiO₂·nH₂O', '澳大利亚、埃塞俄比亚、墨西哥', 'https://mineralseducationcoalition.org/wp-content/uploads/Minerals_Opal-600x600.jpg', '贵蛋白石有变彩效应'),
('Agate', '玛瑙', 'SiO₂', '巴西、乌拉圭、中国辽宁', 'https://mineralseducationcoalition.org/wp-content/uploads/Minerals_Agate-600x600.jpg', '条带状玉髓'),
('Amethyst', '紫水晶', 'SiO₂', '巴西、乌拉圭、赞比亚', 'https://mineralseducationcoalition.org/wp-content/uploads/Minerals_Amethyst-600x600.jpg', '紫色石英'),
('Citrine', '黄水晶', 'SiO₂', '巴西、马达加斯加、乌拉圭', 'https://mineralseducationcoalition.org/wp-content/uploads/Minerals_Citrine-600x600.jpg', '黄色石英');

-- 插入矿物特征数据
-- 硬度特征 (hardness)
INSERT INTO mineral_features (mineral_id, feature_type, feature_value, weight) VALUES
(1, 'hardness', '1', 1.0),
(2, 'hardness', '2', 1.0),
(3, 'hardness', '3', 1.0),
(4, 'hardness', '4', 1.0),
(5, 'hardness', '5', 1.0),
(6, 'hardness', '6', 1.0),
(7, 'hardness', '7', 1.0),
(8, 'hardness', '8', 1.0),
(9, 'hardness', '9', 1.0),
(10, 'hardness', '10', 1.0),
(11, 'hardness', '5', 1.0),
(11, 'hardness', '6', 1.0),
(12, 'hardness', '5', 1.0),
(12, 'hardness', '6', 1.0),
(13, 'hardness', '6', 1.0),
(13, 'hardness', '6.5', 1.0),
(14, 'hardness', '2.5', 1.0),
(15, 'hardness', '3.5', 1.0),
(15, 'hardness', '4', 1.0),
(16, 'hardness', '3.5', 1.0),
(16, 'hardness', '4', 1.0),
(17, 'hardness', '3.5', 1.0),
(17, 'hardness', '4', 1.0),
(18, 'hardness', '3.5', 1.0),
(18, 'hardness', '4', 1.0),
(19, 'hardness', '2', 1.0),
(19, 'hardness', '2.5', 1.0),
(20, 'hardness', '1.5', 1.0),
(20, 'hardness', '2', 1.0),
(21, 'hardness', '1.5', 1.0),
(21, 'hardness', '2', 1.0),
(22, 'hardness', '1', 1.0),
(22, 'hardness', '2', 1.0),
(23, 'hardness', '1.5', 1.0),
(23, 'hardness', '2.5', 1.0),
(24, 'hardness', '6.5', 1.0),
(24, 'hardness', '7', 1.0),
(25, 'hardness', '6.5', 1.0),
(25, 'hardness', '7.5', 1.0),
(26, 'hardness', '4', 1.0),
(26, 'hardness', '7', 1.0),
(27, 'hardness', '6', 1.0),
(27, 'hardness', '7', 1.0),
(28, 'hardness', '5', 1.0),
(28, 'hardness', '5.5', 1.0),
(29, 'hardness', '7', 1.0),
(29, 'hardness', '7.5', 1.0),
(30, 'hardness', '7', 1.0),
(30, 'hardness', '7.5', 1.0),
(31, 'hardness', '7.5', 1.0),
(31, 'hardness', '8', 1.0),
(32, 'hardness', '7.5', 1.0),
(32, 'hardness', '8', 1.0),
(33, 'hardness', '7.5', 1.0),
(33, 'hardness', '8', 1.0),
(34, 'hardness', '6.5', 1.0),
(34, 'hardness', '7.5', 1.0),
(35, 'hardness', '7.5', 1.0),
(35, 'hardness', '8', 1.0),
(36, 'hardness', '8.5', 1.0),
(37, 'hardness', '6.5', 1.0),
(37, 'hardness', '7', 1.0),
(38, 'hardness', '6', 1.0),
(38, 'hardness', '7', 1.0),
(39, 'hardness', '6', 1.0),
(39, 'hardness', '6.5', 1.0),
(40, 'hardness', '5', 1.0),
(40, 'hardness', '6', 1.0),
(41, 'hardness', '3.5', 1.0),
(41, 'hardness', '4', 1.0),
(42, 'hardness', '3.5', 1.0),
(42, 'hardness', '4', 1.0),
(43, 'hardness', '5.5', 1.0),
(43, 'hardness', '6', 1.0),
(44, 'hardness', '6', 1.0),
(44, 'hardness', '6.5', 1.0),
(45, 'hardness', '6', 1.0),
(45, 'hardness', '6.5', 1.0),
(46, 'hardness', '6', 1.0),
(46, 'hardness', '6.5', 1.0),
(47, 'hardness', '5', 1.0),
(47, 'hardness', '6', 1.0),
(48, 'hardness', '5', 1.0),
(48, 'hardness', '6', 1.0),
(49, 'hardness', '6.5', 1.0),
(49, 'hardness', '7', 1.0),
(50, 'hardness', '7', 1.0),
(50, 'hardness', '7.5', 1.0);

-- 条痕色特征 (streak)
INSERT INTO mineral_features (mineral_id, feature_type, feature_value, weight) VALUES
(1, 'streak', 'white', 1.0),
(2, 'streak', 'white', 1.0),
(3, 'streak', 'white', 1.0),
(4, 'streak', 'white', 1.0),
(5, 'streak', 'white', 1.0),
(6, 'streak', 'white', 1.0),
(7, 'streak', 'white', 1.0),
(8, 'streak', 'white', 1.0),
(9, 'streak', 'white', 1.0),
(10, 'streak', 'white', 1.0),
(11, 'streak', 'reddish_brown', 1.0),
(12, 'streak', 'black', 1.0),
(13, 'streak', 'greenish_black', 1.0),
(14, 'streak', 'gray', 1.0),
(15, 'streak', 'yellowish_white', 1.0),
(16, 'streak', 'greenish_black', 1.0),
(17, 'streak', 'green', 1.0),
(18, 'streak', 'blue', 1.0),
(19, 'streak', 'red', 1.0),
(20, 'streak', 'orange_red', 1.0),
(21, 'streak', 'yellow', 1.0),
(22, 'streak', 'gray', 1.0),
(22, 'streak', 'black', 1.0),
(23, 'streak', 'yellow', 1.0),
(23, 'streak', 'white', 1.0),
(24, 'streak', 'white', 1.0),
(24, 'streak', 'yellowish_green', 1.0),
(25, 'streak', 'white', 1.0),
(26, 'streak', 'white', 1.0),
(27, 'streak', 'white', 1.0),
(28, 'streak', 'white', 1.0),
(29, 'streak', 'gray', 1.0),
(29, 'streak', 'white', 1.0),
(30, 'streak', 'white', 1.0),
(31, 'streak', 'white', 1.0),
(32, 'streak', 'white', 1.0),
(33, 'streak', 'white', 1.0),
(34, 'streak', 'white', 1.0),
(35, 'streak', 'white', 1.0),
(36, 'streak', 'white', 1.0),
(37, 'streak', 'white', 1.0),
(37, 'streak', 'yellowish_green', 1.0),
(38, 'streak', 'white', 1.0),
(39, 'streak', 'white', 1.0),
(40, 'streak', 'white', 1.0),
(40, 'streak', 'greenish_white', 1.0),
(41, 'streak', 'greenish_white', 1.0),
(41, 'streak', 'white', 1.0),
(42, 'streak', 'white', 1.0),
(43, 'streak', 'white', 1.0),
(44, 'streak', 'white', 1.0),
(45, 'streak', 'white', 1.0),
(46, 'streak', 'white', 1.0),
(47, 'streak', 'white', 1.0),
(47, 'streak', 'gray', 1.0),
(48, 'streak', 'white', 1.0),
(49, 'streak', 'white', 1.0),
(50, 'streak', 'white', 1.0);

-- 光泽特征 (luster)
INSERT INTO mineral_features (mineral_id, feature_type, feature_value, weight) VALUES
(1, 'luster', 'greasy', 1.0),
(1, 'luster', 'pearly', 1.0),
(2, 'luster', 'glassy', 1.0),
(2, 'luster', 'pearly', 1.0),
(3, 'luster', 'glassy', 1.0),
(4, 'luster', 'glassy', 1.0),
(5, 'luster', 'glassy', 1.0),
(5, 'luster', 'submetallic', 1.0),
(6, 'luster', 'glassy', 1.0),
(7, 'luster', 'glassy', 1.0),
(8, 'luster', 'glassy', 1.0),
(8, 'luster', 'adamantine', 1.0),
(9, 'luster', 'adamantine', 1.0),
(9, 'luster', 'glassy', 1.0),
(10, 'luster', 'adamantine', 1.0),
(11, 'luster', 'metallic', 1.0),
(11, 'luster', 'dull', 1.0),
(12, 'luster', 'metallic', 1.0),
(13, 'luster', 'metallic', 1.0),
(14, 'luster', 'metallic', 1.0),
(15, 'luster', 'resinous', 1.0),
(15, 'luster', 'adamantine', 1.0),
(16, 'luster', 'metallic', 1.0),
(17, 'luster', 'glassy', 1.0),
(17, 'luster', 'dull', 1.0),
(18, 'luster', 'glassy', 1.0),
(18, 'luster', 'dull', 1.0),
(19, 'luster', 'adamantine', 1.0),
(19, 'luster', 'glassy', 1.0),
(20, 'luster', 'resinous', 1.0),
(20, 'luster', 'greasy', 1.0),
(21, 'luster', 'resinous', 1.0),
(21, 'luster', 'greasy', 1.0),
(22, 'luster', 'metallic', 1.0),
(22, 'luster', 'dull', 1.0),
(23, 'luster', 'resinous', 1.0),
(24, 'luster', 'glassy', 1.0),
(25, 'luster', 'vitreous', 1.0),
(25, 'luster', 'resinous', 1.0),
(26, 'luster', 'glassy', 1.0),
(27, 'luster', 'glassy', 1.0),
(28, 'luster', 'glassy', 1.0),
(29, 'luster', 'glassy', 1.0),
(30, 'luster', 'glassy', 1.0),
(30, 'luster', 'resinous', 1.0),
(31, 'luster', 'glassy', 1.0),
(31, 'luster', 'vitreous', 1.0),
(32, 'luster', 'glassy', 1.0),
(33, 'luster', 'glassy', 1.0),
(34, 'luster', 'adamantine', 1.0),
(35, 'luster', 'vitreous', 1.0),
(36, 'luster', 'glassy', 1.0),
(37, 'luster', 'glassy', 1.0),
(38, 'luster', 'glassy', 1.0),
(39, 'luster', 'greasy', 1.0),
(40, 'luster', 'glassy', 1.0),
(41, 'luster', 'waxy', 1.0),
(41, 'luster', 'glassy', 1.0),
(42, 'luster', 'glassy', 1.0),
(43, 'luster', 'glassy', 1.0),
(44, 'luster', 'glassy', 1.0),
(45, 'luster', 'schiller', 1.0),
(46, 'luster', 'pearly', 1.0),
(46, 'luster', 'adularescence', 1.0),
(47, 'luster', 'glassy', 1.0),
(47, 'luster', 'dull', 1.0),
(48, 'luster', 'subvitreous', 1.0),
(48, 'luster', 'greasy', 1.0),
(49, 'luster', 'waxy', 1.0),
(49, 'luster', 'glassy', 1.0),
(50, 'luster', 'glassy', 1.0);

-- 解理特征 (cleavage)
INSERT INTO mineral_features (mineral_id, feature_type, feature_value, weight) VALUES
(1, 'cleavage', 'perfect', 1.0),
(1, 'cleavage', 'basal', 1.0),
(2, 'cleavage', 'perfect', 1.0),
(2, 'cleavage', 'basal', 1.0),
(3, 'cleavage', 'perfect', 1.0),
(3, 'cleavage', 'rhombohedral', 1.0),
(4, 'cleavage', 'perfect', 1.0),
(4, 'cleavage', 'octahedral', 1.0),
(5, 'cleavage', 'imperfect', 1.0),
(5, 'cleavage', 'poor', 1.0),
(6, 'cleavage', 'perfect', 1.0),
(6, 'cleavage', 'basal', 1.0),
(7, 'cleavage', 'absent', 1.0),
(7, 'cleavage', 'conchoidal_fracture', 1.0),
(8, 'cleavage', 'perfect', 1.0),
(8, 'cleavage', 'basal', 1.0),
(9, 'cleavage', 'absent', 1.0),
(9, 'cleavage', 'parting', 1.0),
(10, 'cleavage', 'perfect', 1.0),
(10, 'cleavage', 'octahedral', 1.0),
(11, 'cleavage', 'absent', 1.0),
(11, 'cleavage', 'subconchoidal', 1.0),
(12, 'cleavage', 'indistinct', 1.0),
(13, 'cleavage', 'absent', 1.0),
(13, 'cleavage', 'conchoidal', 1.0),
(14, 'cleavage', 'perfect', 1.0),
(14, 'cleavage', 'cubic', 1.0),
(15, 'cleavage', 'perfect', 1.0),
(15, 'cleavage', 'dodecahedral', 1.0),
(16, 'cleavage', 'indistinct', 1.0),
(17, 'cleavage', 'perfect', 1.0),
(17, 'cleavage', 'basal', 1.0),
(18, 'cleavage', 'perfect', 1.0),
(18, 'cleavage', 'basal', 1.0),
(19, 'cleavage', 'perfect', 1.0),
(19, 'cleavage', 'prismatic', 1.0),
(20, 'cleavage', 'indistinct', 1.0),
(21, 'cleavage', 'perfect', 1.0),
(21, 'cleavage', 'basal', 1.0),
(22, 'cleavage', 'perfect', 1.0),
(22, 'cleavage', 'basal', 1.0),
(23, 'cleavage', 'imperfect', 1.0),
(24, 'cleavage', 'indistinct', 1.0),
(25, 'cleavage', 'indistinct', 1.0),
(26, 'cleavage', 'perfect', 1.0),
(26, 'cleavage', 'pinacoidal', 1.0),
(27, 'cleavage', 'perfect', 1.0),
(28, 'cleavage', 'good', 1.0),
(29, 'cleavage', 'distinct', 1.0),
(30, 'cleavage', 'indistinct', 1.0),
(31, 'cleavage', 'imperfect', 1.0),
(32, 'cleavage', 'imperfect', 1.0),
(33, 'cleavage', 'imperfect', 1.0),
(34, 'cleavage', 'poor', 1.0),
(35, 'cleavage', 'absent', 1.0),
(36, 'cleavage', 'poor', 1.0),
(37, 'cleavage', 'indistinct', 1.0),
(38, 'cleavage', 'good', 1.0),
(39, 'cleavage', 'good', 1.0),
(40, 'cleavage', 'poor', 1.0),
(41, 'cleavage', 'perfect', 1.0),
(42, 'cleavage', 'good', 1.0),
(43, 'cleavage', 'good', 1.0),
(44, 'cleavage', 'good', 1.0),
(45, 'cleavage', 'good', 1.0),
(46, 'cleavage', 'perfect', 1.0),
(47, 'cleavage', 'absent', 1.0),
(48, 'cleavage', 'absent', 1.0),
(49, 'cleavage', 'absent', 1.0),
(50, 'cleavage', 'absent', 1.0);
