#pragma once

#include <string>
#include <vector>
#include <sstream>
#include <unordered_map>
#include "common/types.h"

namespace wps {

class LuaCodeGenerator {
public:
    LuaCodeGenerator() = default;

    std::string generate_plugin(const ProtocolDescriptor& descriptor,
                               const std::vector<HeuristicRule>& rules = {}) {
        std::stringstream lua;
        
        lua << generate_header(descriptor);
        lua << generate_protocol_definition(descriptor);
        lua << generate_field_definitions(descriptor);
        lua << generate_reassembly_function(descriptor);
        lua << generate_parse_function(descriptor);
        lua << generate_heuristic_function(descriptor, rules);
        lua << generate_registration(descriptor);
        
        return lua.str();
    }

    std::string generate_plugin_to_file(const ProtocolDescriptor& descriptor,
                                       const std::string& output_path,
                                       const std::vector<HeuristicRule>& rules = {}) {
        std::string code = generate_plugin(descriptor, rules);
        std::ofstream file(output_path);
        if (!file.is_open()) {
            throw std::runtime_error("Failed to open output file: " + output_path);
        }
        file << code;
        file.close();
        return output_path;
    }

private:
    std::string generate_header(const ProtocolDescriptor& descriptor) {
        std::stringstream ss;
        ss << "-- Wireshark dissector plugin for " << descriptor.display_name << "\n";
        ss << "-- Auto-generated by Wireshark Plugin Suite\n";
        ss << "-- Protocol: " << descriptor.name << "\n";
        ss << "-- Date: " << current_date_string() << "\n\n";
        ss << "local " << descriptor.short_name << " = Proto(\"" << descriptor.short_name 
           << "\", \"" << descriptor.display_name << "\")\n\n";
        return ss.str();
    }

    std::string generate_protocol_definition(const ProtocolDescriptor& descriptor) {
        std::stringstream ss;
        ss << "-- Protocol fields\n";
        ss << "local f = " << descriptor.short_name << ".fields\n\n";
        return ss.str();
    }

    std::string generate_field_definitions(const ProtocolDescriptor& descriptor) {
        std::stringstream ss;
        
        for (const auto& field : descriptor.fields) {
            std::string lua_type = get_lua_field_type(field.type);
            std::string base_type = get_lua_base_type(field.type);
            
            if (field.is_variable_length && field.type == FieldType::STRING) {
                ss << "f." << field.name << " = ProtoField." << lua_type 
                   << "(\"" << descriptor.short_name << "." << field.filter_name 
                   << "\", \"" << field.display_name << "\"";
                if (!base_type.empty()) {
                    ss << ", base." << base_type;
                }
                ss << ")\n";
            } else {
                ss << "f." << field.name << " = ProtoField." << lua_type 
                   << "(\"" << descriptor.short_name << "." << field.filter_name 
                   << "\", \"" << field.display_name << "\"";
                if (!base_type.empty()) {
                    ss << ", base." << base_type;
                }
                ss << ")\n";
            }
            
            if (!field.valid_values.empty()) {
                ss << "local " << field.name << "_vals = {";
                bool first = true;
                for (uint64_t val : field.valid_values) {
                    if (!first) ss << ", ";
                    ss << "[" << val << "] = \"" << field.display_name << " " << val << "\"";
                    first = false;
                }
                ss << "}\n";
            }
        }
        
        ss << "\n";
        return ss.str();
    }

    std::string generate_reassembly_function(const ProtocolDescriptor& descriptor) {
        std::stringstream ss;
        
        ss << "-- TCP reassembly\n";
        ss << "local function dissect_" << descriptor.short_name 
           << "_tcp(tvb, pinfo, tree, offset, len)\n";
        ss << "    local dissect_tbl = DissectorTable.get(\"tcp.port\")\n";
        ss << "    local dissector = dissect_tbl:get_dissector(" 
           << descriptor.default_port_tcp << ")\n\n";
        
        if (descriptor.requires_reassembly) {
            ss << "    -- Handle TCP reassembly\n";
            ss << "    local bytes_remaining = tvb:len() - offset\n";
            ss << "    local desegment_len = 0\n";
            ss << "    local desegment_offset = 0\n\n";
            
            ss << "    -- Try to determine PDU length\n";
            ss << "    if bytes_remaining >= 4 then\n";
            ss << "        -- Assume first 4 bytes contain length\n";
            ss << "        local msg_len = tvb(offset, 4):uint()\n";
            ss << "        local total_len = msg_len + 4\n\n";
            
            ss << "        if bytes_remaining < total_len then\n";
            ss << "            -- Need more bytes\n";
            ss << "            desegment_len = total_len - bytes_remaining\n";
            ss << "            pinfo.desegment_offset = offset\n";
            ss << "            pinfo.desegment_len = desegment_len\n";
            ss << "            return offset + bytes_remaining\n";
            ss << "        end\n";
            ss << "    end\n\n";
        }
        
        ss << "    -- Call the actual dissector\n";
        ss << "    return dissect_" << descriptor.short_name << "_pdu(tvb, pinfo, tree, offset, len)\n";
        ss << "end\n\n";
        
        return ss.str();
    }

    std::string generate_parse_function(const ProtocolDescriptor& descriptor) {
        std::stringstream ss;
        
        ss << "-- Main PDU dissector\n";
        ss << "function dissect_" << descriptor.short_name 
           << "_pdu(tvb, pinfo, tree, offset, len)\n";
        ss << "    if len == nil then len = tvb:len() - offset end\n\n";
        
        ss << "    -- Update protocol column\n";
        ss << "    pinfo.cols.protocol = \"" << descriptor.short_name << "\"\n";
        ss << "    pinfo.cols.info = \"" << descriptor.display_name << " Protocol\"\n\n";
        
        ss << "    -- Create protocol tree\n";
        ss << "    local subtree = tree:add(" << descriptor.short_name 
           << ", tvb(offset, len))\n\n";
        
        ss << "    local current_offset = offset\n";
        ss << "    local field_values = {}\n\n";
        
        for (size_t i = 0; i < descriptor.fields.size(); i++) {
            const auto& field = descriptor.fields[i];
            
            if (!field.depends_on_field.empty()) {
                ss << "    -- Check dependency for " << field.name << "\n";
                ss << "    local dep_val = field_values[\"" << field.depends_on_field << "\"]\n";
                ss << "    if dep_val ~= nil and " 
                   << generate_lua_condition(field.depends_on_condition, "dep_val") << " then\n";
            }
            
            ss << "    -- Parse " << field.display_name << " (" << field.name << ")\n";
            
            if (field.is_variable_length && !field.length_field.empty()) {
                ss << "    local " << field.name << "_len = field_values[\"" 
                   << field.length_field << "\"]\n";
                ss << "    if " << field.name << "_len ~= nil then\n";
                
                if (field.type == FieldType::STRING) {
                    ss << "        local " << field.name << "_tvb = tvb(current_offset, " 
                       << field.name << "_len)\n";
                    ss << "        subtree:add(f." << field.name << ", " 
                       << field.name << "_tvb)\n";
                    ss << "        field_values[\"" << field.name << "\"] = " 
                       << field.name << "_tvb:string()\n";
                } else {
                    ss << "        subtree:add(f." << field.name 
                       << ", tvb(current_offset, " << field.name << "_len))\n";
                    ss << "        field_values[\"" << field.name << "\"] = tvb(current_offset, " 
                       << field.name << "_len)\n";
                }
                ss << "        current_offset = current_offset + " << field.name << "_len\n";
                ss << "    end\n";
            } else {
                std::string get_method = get_lua_get_method(field.type);
                if (field.offset != static_cast<uint32_t>(-1)) {
                    ss << "    local " << field.name << "_offset = offset + " 
                       << field.offset << "\n";
                    ss << "    subtree:add(f." << field.name 
                       << ", tvb(" << field.name << "_offset, " << field.length << "))\n";
                    ss << "    field_values[\"" << field.name << "\"] = tvb(" 
                       << field.name << "_offset, " << field.length << "):" 
                       << get_method << "()\n";
                    ss << "    if current_offset < " << field.name << "_offset + " 
                       << field.length << " then\n";
                    ss << "        current_offset = " << field.name << "_offset + " 
                       << field.length << "\n";
                    ss << "    end\n";
                } else {
                    ss << "    subtree:add(f." << field.name 
                       << ", tvb(current_offset, " << field.length << "))\n";
                    ss << "    field_values[\"" << field.name << "\"] = tvb(current_offset, " 
                       << field.length << "):" << get_method << "()\n";
                    ss << "    current_offset = current_offset + " << field.length << "\n";
                }
            }
            
            if (!field.depends_on_field.empty()) {
                ss << "    end\n";
            }
            
            ss << "\n";
        }
        
        ss << "    return current_offset\n";
        ss << "end\n\n";
        
        ss << "-- Main dissector function\n";
        ss << "function " << descriptor.short_name << ".dissector(tvb, pinfo, tree)\n";
        ss << "    local offset = 0\n";
        ss << "    local len = tvb:len()\n\n";
        
        if (descriptor.requires_reassembly) {
            ss << "    -- Use TCP reassembly if needed\n";
            ss << "    if pinfo.port_type == 2 then  -- TCP\n";
            ss << "        dissect_" << descriptor.short_name 
               << "_tcp(tvb, pinfo, tree, offset, len)\n";
            ss << "    else\n";
            ss << "        dissect_" << descriptor.short_name 
               << "_pdu(tvb, pinfo, tree, offset, len)\n";
            ss << "    end\n";
        } else {
            ss << "    dissect_" << descriptor.short_name 
               << "_pdu(tvb, pinfo, tree, offset, len)\n";
        }
        
        ss << "end\n\n";
        
        return ss.str();
    }

    std::string generate_heuristic_function(const ProtocolDescriptor& descriptor,
                                           const std::vector<HeuristicRule>& rules) {
        std::stringstream ss;
        
        if (rules.empty()) {
            return ss.str();
        }
        
        ss << "-- Heuristic dissector\n";
        ss << "function " << descriptor.short_name << ".heuristic(tvb, pinfo, tree)\n";
        ss << "    -- Check heuristic rules\n";
        ss << "    local total_weight = 0\n";
        ss << "    local matched_weight = 0\n\n";
        
        for (const auto& rule : rules) {
            ss << "    -- Rule: " << rule.name << "\n";
            ss << "    total_weight = total_weight + " << rule.weight << "\n";
            
            switch (rule.type) {
                case HeuristicRule::RuleType::FIXED_BYTES:
                    ss << "    do\n";
                    ss << "        local matched = true\n";
                    ss << "        local expected_bytes = {";
                    for (size_t i = 0; i < rule.expected_bytes.size(); i++) {
                        if (i > 0) ss << ", ";
                        ss << "0x" << std::hex << static_cast<int>(rule.expected_bytes[i]) << std::dec;
                    }
                    ss << "}\n";
                    ss << "        if tvb:len() >= " << rule.offset + rule.expected_bytes.size() << " then\n";
                    ss << "            for i = 1, " << rule.expected_bytes.size() << " do\n";
                    ss << "                if tvb(" << rule.offset << " + i - 1, 1):uint() ~= expected_bytes[i] then\n";
                    ss << "                    matched = false\n";
                    ss << "                    break\n";
                    ss << "                end\n";
                    ss << "            end\n";
                    ss << "        else\n";
                    ss << "            matched = false\n";
                    ss << "        end\n";
                    ss << "        if matched then\n";
                    ss << "            matched_weight = matched_weight + " << rule.weight << "\n";
                    ss << "        end\n";
                    ss << "    end\n";
                    break;
                    
                case HeuristicRule::RuleType::PORT_RANGE:
                    ss << "    if (pinfo.src_port >= " << rule.port_min 
                       << " and pinfo.src_port <= " << rule.port_max << ") or\n";
                    ss << "       (pinfo.dst_port >= " << rule.port_min 
                       << " and pinfo.dst_port <= " << rule.port_max << ") then\n";
                    ss << "        matched_weight = matched_weight + " << rule.weight << "\n";
                    ss << "    end\n";
                    break;
                    
                case HeuristicRule::RuleType::ENTROPY_RANGE:
                    ss << "    -- Entropy check (simplified)\n";
                    ss << "    local data_len = tvb:len() - " << rule.offset << "\n";
                    ss << "    if data_len > 0 then\n";
                    ss << "        matched_weight = matched_weight + " << rule.weight * 0.5 << "\n";
                    ss << "    end\n";
                    break;
                    
                default:
                    break;
            }
            ss << "\n";
        }
        
        ss << "    -- If confidence is high enough, dissect the packet\n";
        ss << "    if total_weight > 0 and (matched_weight / total_weight) >= 0.7 then\n";
        ss << "        " << descriptor.short_name << ".dissector(tvb, pinfo, tree)\n";
        ss << "        return true\n";
        ss << "    end\n";
        ss << "    return false\n";
        ss << "end\n\n";
        
        return ss.str();
    }

    std::string generate_registration(const ProtocolDescriptor& descriptor) {
        std::stringstream ss;
        
        ss << "-- Register the dissector\n";
        ss << "local tcp_port = DissectorTable.get(\"tcp.port\")\n";
        ss << "local udp_port = DissectorTable.get(\"udp.port\")\n\n";
        
        if (descriptor.default_port_tcp > 0) {
            ss << "tcp_port:add(" << descriptor.default_port_tcp << ", " 
               << descriptor.short_name << ")\n";
        }
        if (descriptor.default_port_udp > 0) {
            ss << "udp_port:add(" << descriptor.default_port_udp << ", " 
               << descriptor.short_name << ")\n";
        }
        
        ss << "\n-- Register heuristic dissector\n";
        ss << descriptor.short_name << ":register_heuristic(\"tcp\", " 
           << descriptor.short_name << ".heuristic)\n";
        ss << descriptor.short_name << ":register_heuristic(\"udp\", " 
           << descriptor.short_name << ".heuristic)\n";
        
        return ss.str();
    }

    std::string get_lua_field_type(FieldType type) {
        switch (type) {
            case FieldType::UINT8: return "uint8";
            case FieldType::UINT16: return "uint16";
            case FieldType::UINT32: return "uint32";
            case FieldType::UINT64: return "uint64";
            case FieldType::INT8: return "int8";
            case FieldType::INT16: return "int16";
            case FieldType::INT32: return "int32";
            case FieldType::INT64: return "int64";
            case FieldType::STRING: return "string";
            case FieldType::IPV4: return "ipv4";
            case FieldType::IPV6: return "ipv6";
            case FieldType::MAC: return "ether";
            case FieldType::BYTES: return "bytes";
            case FieldType::VARIABLE: return "bytes";
        }
        return "bytes";
    }

    std::string get_lua_base_type(FieldType type) {
        switch (type) {
            case FieldType::UINT8:
            case FieldType::UINT16:
            case FieldType::UINT32:
            case FieldType::UINT64:
                return "DEC";
            case FieldType::INT8:
            case FieldType::INT16:
            case FieldType::INT32:
            case FieldType::INT64:
                return "DEC";
            default:
                return "";
        }
    }

    std::string get_lua_get_method(FieldType type) {
        switch (type) {
            case FieldType::UINT8: return "uint";
            case FieldType::UINT16: return "uint";
            case FieldType::UINT32: return "uint";
            case FieldType::UINT64: return "uint64";
            case FieldType::INT8: return "int";
            case FieldType::INT16: return "int";
            case FieldType::INT32: return "int";
            case FieldType::INT64: return "int64";
            case FieldType::STRING: return "string";
            case FieldType::IPV4: return "ipv4";
            case FieldType::IPV6: return "ipv6";
            case FieldType::MAC: return "ether";
            default: return "string";
        }
    }

    std::string generate_lua_condition(const std::string& condition, const std::string& var_name) {
        std::string result = condition;
        size_t pos = 0;
        while ((pos = result.find("==", pos)) != std::string::npos) {
            result.replace(pos, 2, " == ");
            pos += 4;
        }
        pos = 0;
        while ((pos = result.find("!=", pos)) != std::string::npos) {
            result.replace(pos, 2, " ~= ");
            pos += 4;
        }
        return result;
    }

    std::string current_date_string() {
        auto now = std::chrono::system_clock::now();
        std::time_t time = std::chrono::system_clock::to_time_t(now);
        std::tm tm;
        localtime_s(&tm, &time);
        char buf[64];
        std::strftime(buf, sizeof(buf), "%Y-%m-%d %H:%M:%S", &tm);
        return std::string(buf);
    }
};

}
