const KeyCodes = {
    basic: [
        { code: 0x00, name: 'KC_NO', label: '无' },
        { code: 0x04, name: 'KC_A', label: 'A' },
        { code: 0x05, name: 'KC_B', label: 'B' },
        { code: 0x06, name: 'KC_C', label: 'C' },
        { code: 0x07, name: 'KC_D', label: 'D' },
        { code: 0x08, name: 'KC_E', label: 'E' },
        { code: 0x09, name: 'KC_F', label: 'F' },
        { code: 0x0A, name: 'KC_G', label: 'G' },
        { code: 0x0B, name: 'KC_H', label: 'H' },
        { code: 0x0C, name: 'KC_I', label: 'I' },
        { code: 0x0D, name: 'KC_J', label: 'J' },
        { code: 0x0E, name: 'KC_K', label: 'K' },
        { code: 0x0F, name: 'KC_L', label: 'L' },
        { code: 0x10, name: 'KC_M', label: 'M' },
        { code: 0x11, name: 'KC_N', label: 'N' },
        { code: 0x12, name: 'KC_O', label: 'O' },
        { code: 0x13, name: 'KC_P', label: 'P' },
        { code: 0x14, name: 'KC_Q', label: 'Q' },
        { code: 0x15, name: 'KC_R', label: 'R' },
        { code: 0x16, name: 'KC_S', label: 'S' },
        { code: 0x17, name: 'KC_T', label: 'T' },
        { code: 0x18, name: 'KC_U', label: 'U' },
        { code: 0x19, name: 'KC_V', label: 'V' },
        { code: 0x1A, name: 'KC_W', label: 'W' },
        { code: 0x1B, name: 'KC_X', label: 'X' },
        { code: 0x1C, name: 'KC_Y', label: 'Y' },
        { code: 0x1D, name: 'KC_Z', label: 'Z' },
        { code: 0x1E, name: 'KC_1', label: '1' },
        { code: 0x1F, name: 'KC_2', label: '2' },
        { code: 0x20, name: 'KC_3', label: '3' },
        { code: 0x21, name: 'KC_4', label: '4' },
        { code: 0x22, name: 'KC_5', label: '5' },
        { code: 0x23, name: 'KC_6', label: '6' },
        { code: 0x24, name: 'KC_7', label: '7' },
        { code: 0x25, name: 'KC_8', label: '8' },
        { code: 0x26, name: 'KC_9', label: '9' },
        { code: 0x27, name: 'KC_0', label: '0' },
        { code: 0x28, name: 'KC_ENTER', label: '回车' },
        { code: 0x29, name: 'KC_ESCAPE', label: 'ESC' },
        { code: 0x2A, name: 'KC_BSPACE', label: '退格' },
        { code: 0x2B, name: 'KC_TAB', label: 'Tab' },
        { code: 0x2C, name: 'KC_SPACE', label: '空格' },
        { code: 0x2D, name: 'KC_MINUS', label: '-_' },
        { code: 0x2E, name: 'KC_EQUAL', label: '=+' },
        { code: 0x2F, name: 'KC_LBRACKET', label: '[{' },
        { code: 0x30, name: 'KC_RBRACKET', label: ']}' },
        { code: 0x31, name: 'KC_BSLASH', label: '\\|' },
        { code: 0x33, name: 'KC_SCOLON', label: ';:' },
        { code: 0x34, name: 'KC_QUOTE', label: "'\"" },
        { code: 0x35, name: 'KC_GRAVE', label: '`~' },
        { code: 0x36, name: 'KC_COMMA', label: ',<' },
        { code: 0x37, name: 'KC_DOT', label: '.>' },
        { code: 0x38, name: 'KC_SLASH', label: '/?' },
        { code: 0x39, name: 'KC_CAPS', label: '大写' }
    ],
    modifier: [
        { code: 0xE0, name: 'KC_LCTRL', label: '左Ctrl' },
        { code: 0xE1, name: 'KC_LSHIFT', label: '左Shift' },
        { code: 0xE2, name: 'KC_LALT', label: '左Alt' },
        { code: 0xE3, name: 'KC_LGUI', label: '左Win' },
        { code: 0xE4, name: 'KC_RCTRL', label: '右Ctrl' },
        { code: 0xE5, name: 'KC_RSHIFT', label: '右Shift' },
        { code: 0xE6, name: 'KC_RALT', label: '右Alt' },
        { code: 0xE7, name: 'KC_RGUI', label: '右Win' }
    ],
    function: [
        { code: 0x3A, name: 'KC_F1', label: 'F1' },
        { code: 0x3B, name: 'KC_F2', label: 'F2' },
        { code: 0x3C, name: 'KC_F3', label: 'F3' },
        { code: 0x3D, name: 'KC_F4', label: 'F4' },
        { code: 0x3E, name: 'KC_F5', label: 'F5' },
        { code: 0x3F, name: 'KC_F6', label: 'F6' },
        { code: 0x40, name: 'KC_F7', label: 'F7' },
        { code: 0x41, name: 'KC_F8', label: 'F8' },
        { code: 0x42, name: 'KC_F9', label: 'F9' },
        { code: 0x43, name: 'KC_F10', label: 'F10' },
        { code: 0x44, name: 'KC_F11', label: 'F11' },
        { code: 0x45, name: 'KC_F12', label: 'F12' },
        { code: 0x46, name: 'KC_PSCREEN', label: '截屏' },
        { code: 0x47, name: 'KC_SCROLLLOCK', label: '滚动' },
        { code: 0x48, name: 'KC_PAUSE', label: '暂停' },
        { code: 0x49, name: 'KC_INSERT', label: '插入' },
        { code: 0x4A, name: 'KC_HOME', label: 'Home' },
        { code: 0x4B, name: 'KC_PGUP', label: 'PgUp' },
        { code: 0x4C, name: 'KC_DELETE', label: 'Delete' },
        { code: 0x4D, name: 'KC_END', label: 'End' },
        { code: 0x4E, name: 'KC_PGDOWN', label: 'PgDn' },
        { code: 0x4F, name: 'KC_RIGHT', label: '→' },
        { code: 0x50, name: 'KC_LEFT', label: '←' },
        { code: 0x51, name: 'KC_DOWN', label: '↓' },
        { code: 0x52, name: 'KC_UP', label: '↑' }
    ],
    media: [
        { code: 0xE8, name: 'KC_MUTE', label: '静音' },
        { code: 0xE9, name: 'KC_VOLU', label: '音量+' },
        { code: 0xEA, name: 'KC_VOLD', label: '音量-' },
        { code: 0xEB, name: 'KC_MNXT', label: '下一曲' },
        { code: 0xEC, name: 'KC_MPRV', label: '上一曲' },
        { code: 0xED, name: 'KC_MSTP', label: '停止' },
        { code: 0xEE, name: 'KC_MPLY', label: '播放' },
        { code: 0xEF, name: 'KC_MSEL', label: '媒体' },
        { code: 0xF0, name: 'KC_EJCT', label: '弹出' },
        { code: 0xF1, name: 'KC_CALC', label: '计算器' },
        { code: 0xF2, name: 'KC_MAIL', label: '邮件' },
        { code: 0xF3, name: 'KC_MYCM', label: '我的电脑' },
        { code: 0xF4, name: 'KC_WSCH', label: '搜索' },
        { code: 0xF5, name: 'KC_WHOM', label: '主页' },
        { code: 0xF6, name: 'KC_WBAK', label: '返回' },
        { code: 0xF7, name: 'KC_WFWD', label: '前进' },
        { code: 0xF8, name: 'KC_WSTP', label: '停止' },
        { code: 0xF9, name: 'KC_WREF', label: '刷新' },
        { code: 0xFA, name: 'KC_WFAV', label: '收藏' }
    ],
    layer: [
        { code: 0x5100, name: 'MO(0)', label: 'MO 0' },
        { code: 0x5101, name: 'MO(1)', label: 'MO 1' },
        { code: 0x5102, name: 'MO(2)', label: 'MO 2' },
        { code: 0x5103, name: 'MO(3)', label: 'MO 3' },
        { code: 0x5200, name: 'TG(0)', label: 'TG 0' },
        { code: 0x5201, name: 'TG(1)', label: 'TG 1' },
        { code: 0x5202, name: 'TG(2)', label: 'TG 2' },
        { code: 0x5203, name: 'TG(3)', label: 'TG 3' },
        { code: 0x5000, name: 'TO(0)', label: 'TO 0' },
        { code: 0x5001, name: 'TO(1)', label: 'TO 1' },
        { code: 0x5002, name: 'TO(2)', label: 'TO 2' },
        { code: 0x5003, name: 'TO(3)', label: 'TO 3' },
        { code: 0x5501, name: 'TT(1)', label: 'TT 1' },
        { code: 0x5502, name: 'TT(2)', label: 'TT 2' },
        { code: 0x5503, name: 'TT(3)', label: 'TT 3' },
        { code: 0x5710, name: 'OSL(1)', label: 'OSL 1' },
        { code: 0x5720, name: 'OSL(2)', label: 'OSL 2' },
        { code: 0x5730, name: 'OSL(3)', label: 'OSL 3' }
    ],
    macro: [
        { code: 0x5F00, name: 'M(0)', label: '宏 0' },
        { code: 0x5F01, name: 'M(1)', label: '宏 1' },
        { code: 0x5F02, name: 'M(2)', label: '宏 2' },
        { code: 0x5F03, name: 'M(3)', label: '宏 3' },
        { code: 0x5F04, name: 'M(4)', label: '宏 4' },
        { code: 0x5F05, name: 'M(5)', label: '宏 5' },
        { code: 0x5F06, name: 'M(6)', label: '宏 6' },
        { code: 0x5F07, name: 'M(7)', label: '宏 7' },
        { code: 0x5F08, name: 'M(8)', label: '宏 8' },
        { code: 0x5F09, name: 'M(9)', label: '宏 9' },
        { code: 0x5F0A, name: 'M(10)', label: '宏 10' },
        { code: 0x5F0B, name: 'M(11)', label: '宏 11' },
        { code: 0x5F0C, name: 'M(12)', label: '宏 12' },
        { code: 0x5F0D, name: 'M(13)', label: '宏 13' },
        { code: 0x5F0E, name: 'M(14)', label: '宏 14' },
        { code: 0x5F0F, name: 'M(15)', label: '宏 15' }
    ]
};

function getKeyLabel(code) {
    for (const category of Object.values(KeyCodes)) {
        const key = category.find(k => k.code === code);
        if (key) return key.label;
    }
    return `0x${code.toString(16).toUpperCase()}`;
}