server.port=8080

# MQTT 配置
mqtt.broker.url=tcp://broker.emqx.io:1883
mqtt.client.id=backend_light_control_${random.uuid}
mqtt.topic.control=iot/light/control
mqtt.topic.status=iot/light/status
mqtt.connection.timeout=10
mqtt.keep.alive=20
