spring.application.name=cabinet

spring.data.redis.host=localhost
spring.data.redis.port=6379
spring.data.redis.timeout=5000ms

spring.cache.type=redis
spring.cache.redis.time-to-live=600000

server.port=8080
