import type { Specimen, Seal, Cabinet, CabinetVersion, DiffRecord, AcceptanceRecord } from './types';

export const mockSpecimens: Specimen[] = [
  {
    id: 'spec-001',
    name: '东北虎头骨标本',
    code: 'MAM-2023-001',
    category: '哺乳类',
    originalCabinetId: 'cab-a',
    originalPosition: { row: 1, col: 1 },
    currentPosition: { row: 1, col: 1 },
    status: 'verified',
    checkoutDate: '2024-03-15',
    returnDate: '2024-05-20',
    description: '成年雄性东北虎完整头骨标本',
  },
  {
    id: 'spec-002',
    name: '朱鹮剥制标本',
    code: 'AVI-2023-002',
    category: '鸟类',
    originalCabinetId: 'cab-a',
    originalPosition: { row: 1, col: 2 },
    currentPosition: { row: 1, col: 2 },
    status: 'verified',
    checkoutDate: '2024-03-15',
    returnDate: '2024-05-20',
  },
  {
    id: 'spec-003',
    name: '大熊猫幼崽骨骼',
    code: 'MAM-2023-003',
    category: '哺乳类',
    originalCabinetId: 'cab-a',
    originalPosition: { row: 2, col: 1 },
    currentPosition: { row: 2, col: 1 },
    status: 'verified',
    checkoutDate: '2024-03-15',
    returnDate: '2024-05-20',
  },
  {
    id: 'spec-004',
    name: '扬子鳄浸制标本',
    code: 'REP-2023-004',
    category: '爬行类',
    originalCabinetId: 'cab-a',
    originalPosition: { row: 2, col: 2 },
    currentPosition: undefined,
    status: 'returned',
    checkoutDate: '2024-03-15',
    returnDate: '2024-05-20',
  },
  {
    id: 'spec-005',
    name: '中华鲟标本',
    code: 'PIS-2023-005',
    category: '鱼类',
    originalCabinetId: 'cab-a',
    originalPosition: { row: 3, col: 1 },
    currentPosition: undefined,
    status: 'returned',
    checkoutDate: '2024-03-15',
    returnDate: '2024-05-20',
  },
  {
    id: 'spec-006',
    name: '金斑喙凤蝶',
    code: 'INS-2023-006',
    category: '昆虫类',
    originalCabinetId: 'cab-a',
    originalPosition: { row: 3, col: 2 },
    currentPosition: { row: 3, col: 2 },
    status: 'verified',
    checkoutDate: '2024-03-15',
    returnDate: '2024-05-20',
  },
  {
    id: 'spec-007',
    name: '银杉模式标本',
    code: 'BOT-2023-007',
    category: '植物类',
    originalCabinetId: 'cab-a',
    originalPosition: { row: 4, col: 1 },
    currentPosition: undefined,
    status: 'returned',
    checkoutDate: '2024-03-15',
    returnDate: '2024-05-20',
  },
  {
    id: 'spec-008',
    name: '恐龙蛋化石',
    code: 'PAL-2023-008',
    category: '古生物',
    originalCabinetId: 'cab-a',
    originalPosition: { row: 4, col: 2 },
    currentPosition: undefined,
    status: 'returned',
    checkoutDate: '2024-03-15',
    returnDate: '2024-05-20',
  },
  {
    id: 'spec-009',
    name: '金丝猴剥制标本',
    code: 'MAM-2023-009',
    category: '哺乳类',
    originalCabinetId: 'cab-b',
    originalPosition: { row: 1, col: 1 },
    status: 'in-storage',
  },
  {
    id: 'spec-010',
    name: '褐马鸡标本',
    code: 'AVI-2023-010',
    category: '鸟类',
    originalCabinetId: 'cab-b',
    originalPosition: { row: 1, col: 2 },
    status: 'in-storage',
  },
];

export const mockSeals: Seal[] = [
  {
    id: 'seal-001',
    boxCode: 'BOX-2024-A01',
    specimenIds: ['spec-001', 'spec-002', 'spec-003'],
    sealCode: 'SEAL-A8X7K2',
    sealedAt: '2024-03-15T10:30:00Z',
    status: 'unsealed',
    unsealedAt: '2024-05-20T14:20:00Z',
    destination: '上海自然博物馆',
  },
  {
    id: 'seal-002',
    boxCode: 'BOX-2024-A02',
    specimenIds: ['spec-004', 'spec-005', 'spec-006'],
    sealCode: 'SEAL-B3M9P5',
    sealedAt: '2024-03-15T11:00:00Z',
    status: 'unsealed',
    unsealedAt: '2024-05-20T14:45:00Z',
    destination: '上海自然博物馆',
  },
  {
    id: 'seal-003',
    boxCode: 'BOX-2024-A03',
    specimenIds: ['spec-007', 'spec-008'],
    sealCode: 'SEAL-C2J4N8',
    sealedAt: '2024-03-15T11:30:00Z',
    status: 'unsealed',
    unsealedAt: '2024-05-20T15:00:00Z',
    destination: '上海自然博物馆',
  },
];

export const mockCabinets: Cabinet[] = [
  {
    id: 'cab-a',
    name: 'A柜 - 珍稀动物区',
    description: '存放国家级保护动物标本',
    rows: 5,
    cols: 3,
    location: '标本馆一层东侧',
    currentVersion: 3,
  },
  {
    id: 'cab-b',
    name: 'B柜 - 鸟类专区',
    description: '存放各类鸟类标本',
    rows: 5,
    cols: 3,
    location: '标本馆一层西侧',
    currentVersion: 2,
  },
  {
    id: 'cab-c',
    name: 'C柜 - 古生物区',
    description: '存放化石及古生物标本',
    rows: 4,
    cols: 4,
    location: '标本馆二层南侧',
    currentVersion: 1,
  },
];

export const mockCabinetVersions: CabinetVersion[] = [
  {
    id: 'ver-001',
    version: 1,
    cabinetId: 'cab-a',
    cabinetName: 'A柜 - 珍稀动物区',
    layout: [
      { position: { row: 1, col: 1 }, specimenId: 'spec-001' },
      { position: { row: 1, col: 2 }, specimenId: 'spec-002' },
      { position: { row: 2, col: 1 }, specimenId: 'spec-003' },
      { position: { row: 2, col: 2 }, specimenId: 'spec-004' },
      { position: { row: 3, col: 1 }, specimenId: 'spec-005' },
      { position: { row: 3, col: 2 }, specimenId: 'spec-006' },
      { position: { row: 4, col: 1 }, specimenId: 'spec-007' },
      { position: { row: 4, col: 2 }, specimenId: 'spec-008' },
    ],
    createdAt: '2024-01-10T08:00:00Z',
    createdBy: '张馆长',
    note: '初始柜位布局',
  },
  {
    id: 'ver-002',
    version: 2,
    cabinetId: 'cab-a',
    cabinetName: 'A柜 - 珍稀动物区',
    layout: [
      { position: { row: 1, col: 1 }, specimenId: undefined },
      { position: { row: 1, col: 2 }, specimenId: undefined },
      { position: { row: 2, col: 1 }, specimenId: undefined },
      { position: { row: 2, col: 2 }, specimenId: undefined },
      { position: { row: 3, col: 1 }, specimenId: undefined },
      { position: { row: 3, col: 2 }, specimenId: undefined },
      { position: { row: 4, col: 1 }, specimenId: undefined },
      { position: { row: 4, col: 2 }, specimenId: undefined },
    ],
    createdAt: '2024-03-15T12:00:00Z',
    createdBy: '李馆员',
    note: '标本借出后柜位清空',
  },
  {
    id: 'ver-003',
    version: 3,
    cabinetId: 'cab-a',
    cabinetName: 'A柜 - 珍稀动物区',
    layout: [
      { position: { row: 1, col: 1 }, specimenId: 'spec-001' },
      { position: { row: 1, col: 2 }, specimenId: 'spec-002' },
      { position: { row: 2, col: 1 }, specimenId: 'spec-003' },
      { position: { row: 2, col: 2 }, specimenId: undefined },
      { position: { row: 3, col: 1 }, specimenId: undefined },
      { position: { row: 3, col: 2 }, specimenId: 'spec-006' },
      { position: { row: 4, col: 1 }, specimenId: undefined },
      { position: { row: 4, col: 2 }, specimenId: undefined },
    ],
    createdAt: '2024-05-20T16:00:00Z',
    createdBy: '王馆员',
    note: '部分标本回库',
  },
];

export const mockDiffs: DiffRecord[] = [
  {
    id: 'diff-001',
    specimenId: 'spec-004',
    specimenName: '扬子鳄浸制标本',
    specimenCode: 'REP-2023-004',
    expectedPosition: { row: 2, col: 2 },
    actualPosition: { row: 5, col: 1 },
    status: 'pending',
    createdAt: '2024-05-20T15:30:00Z',
  },
];

export const mockAcceptances: AcceptanceRecord[] = [
  {
    id: 'acc-001',
    specimenId: 'spec-001',
    specimenName: '东北虎头骨标本',
    specimenCode: 'MAM-2023-001',
    condition: 'good',
    acceptedBy: '王馆员',
    acceptedAt: '2024-05-20T14:30:00Z',
    notes: '标本完好无损，包装完整',
  },
  {
    id: 'acc-002',
    specimenId: 'spec-002',
    specimenName: '朱鹮剥制标本',
    specimenCode: 'AVI-2023-002',
    condition: 'good',
    acceptedBy: '王馆员',
    acceptedAt: '2024-05-20T14:35:00Z',
  },
  {
    id: 'acc-003',
    specimenId: 'spec-003',
    specimenName: '大熊猫幼崽骨骼',
    specimenCode: 'MAM-2023-003',
    condition: 'needs-repair',
    acceptedBy: '王馆员',
    acceptedAt: '2024-05-20T14:40:00Z',
    notes: '下颌骨关节处有松动，需修复',
  },
  {
    id: 'acc-004',
    specimenId: 'spec-004',
    specimenName: '扬子鳄浸制标本',
    specimenCode: 'REP-2023-004',
    condition: 'good',
    acceptedBy: '李馆员',
    acceptedAt: '2024-05-20T15:00:00Z',
  },
  {
    id: 'acc-005',
    specimenId: 'spec-005',
    specimenName: '中华鲟标本',
    specimenCode: 'PIS-2023-005',
    condition: 'damaged',
    acceptedBy: '李馆员',
    acceptedAt: '2024-05-20T15:10:00Z',
    notes: '尾鳍部分有破损，需拍照记录',
  },
  {
    id: 'acc-006',
    specimenId: 'spec-006',
    specimenName: '金斑喙凤蝶',
    specimenCode: 'INS-2023-006',
    condition: 'good',
    acceptedBy: '李馆员',
    acceptedAt: '2024-05-20T15:15:00Z',
  },
  {
    id: 'acc-007',
    specimenId: 'spec-007',
    specimenName: '银杉模式标本',
    specimenCode: 'BOT-2023-007',
    condition: 'good',
    acceptedBy: '张馆员',
    acceptedAt: '2024-05-20T15:30:00Z',
  },
  {
    id: 'acc-008',
    specimenId: 'spec-008',
    specimenName: '恐龙蛋化石',
    specimenCode: 'PAL-2023-008',
    condition: 'good',
    acceptedBy: '张馆员',
    acceptedAt: '2024-05-20T15:35:00Z',
  },
];
