CREATE DATABASE IF NOT EXISTS dorm_bill DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

USE dorm_bill;

CREATE TABLE IF NOT EXISTS dormitory (
    id BIGINT PRIMARY KEY AUTO_INCREMENT,
    dorm_number VARCHAR(50) NOT NULL UNIQUE COMMENT '寝室号',
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
) COMMENT '寝室表';

CREATE TABLE IF NOT EXISTS user (
    id BIGINT PRIMARY KEY AUTO_INCREMENT,
    username VARCHAR(50) NOT NULL UNIQUE COMMENT '用户名',
    password VARCHAR(255) NOT NULL COMMENT '密码',
    nickname VARCHAR(50) COMMENT '昵称',
    dorm_id BIGINT COMMENT '寝室ID',
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    FOREIGN KEY (dorm_id) REFERENCES dormitory(id)
) COMMENT '用户表';

CREATE TABLE IF NOT EXISTS bill (
    id BIGINT PRIMARY KEY AUTO_INCREMENT,
    dorm_id BIGINT NOT NULL COMMENT '寝室ID',
    bill_date VARCHAR(7) NOT NULL COMMENT '账单月份 YYYY-MM',
    electricity_amount DECIMAL(10,2) NOT NULL DEFAULT 0 COMMENT '总电费',
    water_amount DECIMAL(10,2) NOT NULL DEFAULT 0 COMMENT '总水费',
    total_amount DECIMAL(10,2) NOT NULL DEFAULT 0 COMMENT '总金额',
    per_person_amount DECIMAL(10,2) NOT NULL DEFAULT 0 COMMENT '人均金额',
    head_count INT NOT NULL DEFAULT 0 COMMENT '分摊人数',
    created_by BIGINT COMMENT '录入人ID',
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    FOREIGN KEY (dorm_id) REFERENCES dormitory(id),
    FOREIGN KEY (created_by) REFERENCES user(id),
    UNIQUE KEY uk_dorm_date (dorm_id, bill_date)
) COMMENT '账单表';

CREATE TABLE IF NOT EXISTS payment (
    id BIGINT PRIMARY KEY AUTO_INCREMENT,
    bill_id BIGINT NOT NULL COMMENT '账单ID',
    user_id BIGINT NOT NULL COMMENT '用户ID',
    amount DECIMAL(10,2) NOT NULL COMMENT '应缴金额',
    status TINYINT NOT NULL DEFAULT 0 COMMENT '缴费状态 0-未缴 1-已缴',
    paid_at TIMESTAMP NULL COMMENT '缴费时间',
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    FOREIGN KEY (bill_id) REFERENCES bill(id),
    FOREIGN KEY (user_id) REFERENCES user(id),
    UNIQUE KEY uk_bill_user (bill_id, user_id)
) COMMENT '缴费记录表';
