import { BaseGenerator } from './base';
import type {
  ASTNode,
  DelayNode,
  StringNode,
  KeyNode,
  MouseMoveNode,
  MouseClickNode,
  RepeatNode,
  IfOSNode,
  VarNode,
  IncludeNode,
  DeviceType,
} from '@shared/types';

export class BadUSBGenerator extends BaseGenerator {
  protected targetDevice: DeviceType = 'badusb';
  protected fileExtension: string = 'txt';
  protected fileName: string = 'payload';

  protected generateCode(ast: ASTNode[]): string {
    const lines: string[] = [];
    lines.push('REM Generated by HID Attack Framework');
    lines.push('REM Target: BadUSB / Rubber Ducky');
    lines.push('');

    const bodyCode = this.generateNodes(ast, 0);
    if (bodyCode) {
      lines.push(bodyCode);
    }

    return lines.join('\n');
  }

  protected generateDelay(node: DelayNode, indent: number): string {
    const indentStr = this.getIndent(indent);
    return `${indentStr}DELAY ${node.milliseconds}`;
  }

  protected generateString(node: StringNode, indent: number): string {
    const indentStr = this.getIndent(indent);
    const value = this.resolveVariables(node.value);

    if (value.includes('\n')) {
      const lines: string[] = [];
      const parts = value.split('\n');
      parts.forEach((part, index) => {
        if (part.length > 0) {
          lines.push(`${indentStr}STRING ${part}`);
        }
        if (index < parts.length - 1) {
          lines.push(`${indentStr}ENTER`);
        }
      });
      return lines.join('\n');
    }

    return `${indentStr}STRING ${value}`;
  }

  protected generateKey(node: KeyNode, indent: number): string {
    const indentStr = this.getIndent(indent);
    const key = this.mapKeyName(node.key);
    const modifiers = node.modifiers.map((m) => this.mapModifier(m)).filter(Boolean);
    const repeat = node.repeat || 1;

    const keyParts = [...modifiers, key];
    const keyStr = keyParts.join(' ');

    if (repeat > 1) {
      const lines: string[] = [];
      for (let i = 0; i < repeat; i++) {
        lines.push(`${indentStr}${keyStr}`);
      }
      return lines.join('\n');
    }

    return `${indentStr}${keyStr}`;
  }

  protected generateMouseMove(node: MouseMoveNode, indent: number): string {
    const indentStr = this.getIndent(indent);
    return `${indentStr}REM MOUSE_MOVE ${node.x} ${node.y}`;
  }

  protected generateMouseClick(node: MouseClickNode, indent: number): string {
    const indentStr = this.getIndent(indent);
    const buttonMap: Record<string, string> = {
      'left': 'LEFTCLICK',
      'right': 'RIGHTCLICK',
      'middle': 'MIDDLECLICK',
    };
    const button = buttonMap[node.button] || 'LEFTCLICK';
    return `${indentStr}${button}`;
  }

  protected generateRepeat(node: RepeatNode, indent: number): string {
    const indentStr = this.getIndent(indent);
    const lines: string[] = [];
    const bodyCode = this.generateNodes(node.body, indent);

    lines.push(`${indentStr}REM REPEAT ${node.count}`);
    for (let i = 0; i < node.count; i++) {
      if (bodyCode) {
        lines.push(bodyCode);
      }
    }
    lines.push(`${indentStr}REM END_REPEAT`);

    return lines.join('\n');
  }

  protected generateIfOS(node: IfOSNode, indent: number): string {
    const indentStr = this.getIndent(indent);
    const bodyCode = this.generateNodes(node.body, indent);
    const lines: string[] = [];

    lines.push(`${indentStr}REM Target OS: ${node.os}`);
    if (bodyCode) {
      lines.push(bodyCode);
    }

    return lines.join('\n');
  }

  protected generateVar(node: VarNode, indent: number): string {
    this.variables.set(node.name, node.value);
    const indentStr = this.getIndent(indent);
    return `${indentStr}REM VAR ${node.name} = ${node.value}`;
  }

  protected generateInclude(node: IncludeNode, indent: number): string {
    const indentStr = this.getIndent(indent);
    return `${indentStr}REM INCLUDE ${node.template}`;
  }

  private mapModifier(modifier: string): string {
    const modifierMap: Record<string, string> = {
      'CTRL': 'CONTROL',
      'CONTROL': 'CONTROL',
      'SHIFT': 'SHIFT',
      'ALT': 'ALT',
      'GUI': 'GUI',
      'WINDOWS': 'GUI',
      'CMD': 'GUI',
      'COMMAND': 'GUI',
    };
    return modifierMap[modifier.toUpperCase()] || '';
  }

  protected mapKeyName(key: string): string {
    const keyMap: Record<string, string> = {
      'CTRL': 'CONTROL',
      'CONTROL': 'CONTROL',
      'SHIFT': 'SHIFT',
      'ALT': 'ALT',
      'GUI': 'GUI',
      'WINDOWS': 'GUI',
      'CMD': 'GUI',
      'COMMAND': 'GUI',
      'ENTER': 'ENTER',
      'RETURN': 'ENTER',
      'ESC': 'ESC',
      'ESCAPE': 'ESC',
      'BACKSPACE': 'BACKSPACE',
      'BS': 'BACKSPACE',
      'TAB': 'TAB',
      'SPACE': 'SPACE',
      'CAPSLOCK': 'CAPSLOCK',
      'DELETE': 'DELETE',
      'DEL': 'DELETE',
      'INSERT': 'INSERT',
      'INS': 'INSERT',
      'HOME': 'HOME',
      'END': 'END',
      'PAGEUP': 'PAGEUP',
      'PGUP': 'PAGEUP',
      'PAGEDOWN': 'PAGEDOWN',
      'PGDN': 'PAGEDOWN',
      'UP': 'UP',
      'UPARROW': 'UP',
      'DOWN': 'DOWN',
      'DOWNARROW': 'DOWN',
      'LEFT': 'LEFT',
      'LEFTARROW': 'LEFT',
      'RIGHT': 'RIGHT',
      'RIGHTARROW': 'RIGHT',
      'F1': 'F1',
      'F2': 'F2',
      'F3': 'F3',
      'F4': 'F4',
      'F5': 'F5',
      'F6': 'F6',
      'F7': 'F7',
      'F8': 'F8',
      'F9': 'F9',
      'F10': 'F10',
      'F11': 'F11',
      'F12': 'F12',
      'PRINTSCREEN': 'PRINTSCREEN',
      'SCROLLLOCK': 'SCROLLLOCK',
      'PAUSE': 'PAUSE',
      'BREAK': 'PAUSE',
      'MENU': 'MENU',
      'APP': 'MENU',
    };
    return keyMap[key.toUpperCase()] || key.toUpperCase();
  }
}
