"""
Lua Plugin Generator - Generates Wireshark dissector Lua plugins from protocol descriptions
"""

from datetime import datetime
from typing import List, Dict, Any, Optional
from .protocol_description import ProtocolDescription, FieldDescription, HeuristicRule, FieldType


class LuaPluginGenerator:
    """Generates Wireshark Lua dissector plugins"""

    def __init__(self):
        self.template_header = """-- Wireshark dissector plugin for {display_name}
-- Auto-generated by Wireshark Plugin Suite
-- Protocol: {name}
-- Generated: {date}

local {short_name} = Proto("{short_name}", "{display_name}")

"""

        self.template_fields = """-- Protocol fields
local f = {short_name}.fields

"""

        self.template_reassembly = """-- TCP reassembly handler
local function dissect_{short_name}_tcp(tvb, pinfo, tree, offset, len)
    local bytes_remaining = tvb:len() - offset
    local desegment_len = 0
    local desegment_offset = 0

    -- Handle TCP reassembly
    if bytes_remaining >= 4 then
        local msg_len = tvb(offset, 4):uint()
        local total_len = msg_len + 4

        if bytes_remaining < total_len then
            desegment_len = total_len - bytes_remaining
            pinfo.desegment_offset = offset
            pinfo.desegment_len = desegment_len
            return offset + bytes_remaining
        end
    end

    return dissect_{short_name}_pdu(tvb, pinfo, tree, offset, len)
end

"""

    def generate(self, protocol: ProtocolDescription) -> str:
        """Generate complete Lua plugin code"""
        lua_code = []

        lua_code.append(self._generate_header(protocol))
        lua_code.append(self._generate_field_definitions(protocol))
        lua_code.append(self._generate_dissector_function(protocol))
        
        if protocol.requires_reassembly:
            lua_code.append(self._generate_reassembly_function(protocol))
        
        if protocol.heuristic_rules:
            lua_code.append(self._generate_heuristic_function(protocol))
        
        lua_code.append(self._generate_registration(protocol))

        return "\n".join(lua_code)

    def generate_to_file(self, protocol: ProtocolDescription, output_path: str) -> str:
        """Generate Lua plugin and write to file"""
        code = self.generate(protocol)
        with open(output_path, 'w', encoding='utf-8') as f:
            f.write(code)
        return output_path

    def _generate_header(self, protocol: ProtocolDescription) -> str:
        now = datetime.now().strftime("%Y-%m-%d %H:%M:%S")
        return self.template_header.format(
            name=protocol.name,
            display_name=protocol.display_name,
            short_name=protocol.short_name,
            date=now
        )

    def _generate_field_definitions(self, protocol: ProtocolDescription) -> str:
        lines = [self.template_fields.format(short_name=protocol.short_name)]

        for field in protocol.fields:
            lua_type = self._get_lua_field_type(field.type)
            base_type = self._get_lua_base_type(field.type)

            if field.is_variable_length and field.type == FieldType.STRING:
                line = f'f.{field.name} = ProtoField.{lua_type}("{protocol.short_name}.{field.filter_name}", "{field.display_name}"'
            else:
                line = f'f.{field.name} = ProtoField.{lua_type}("{protocol.short_name}.{field.filter_name}", "{field.display_name}"'

            if base_type:
                line += f", base.{base_type}"

            if field.valid_values:
                vals_name = f"{field.name}_vals"
                vals_parts = []
                for val in field.valid_values:
                    vals_parts.append(f"[{val}] = \"{field.display_name} {val}\"")
                lines.append(f"local {vals_name} = {{{', '.join(vals_parts)}}}")
                line += f", {vals_name}"

            line += ")"
            lines.append(line)

        lines.append("\n")
        return "\n".join(lines)

    def _generate_dissector_function(self, protocol: ProtocolDescription) -> str:
        short_name = protocol.short_name
        lines = []

        lines.append(f"-- Main PDU dissector function")
        lines.append(f"function dissect_{short_name}_pdu(tvb, pinfo, tree, offset, len)")
        lines.append(f"    if len == nil then len = tvb:len() - offset end")
        lines.append("")
        lines.append(f"    pinfo.cols.protocol = \"{short_name.upper()}\"")
        lines.append(f"    pinfo.cols.info = \"{protocol.display_name}\"")
        lines.append("")
        lines.append(f"    local subtree = tree:add({short_name}, tvb(offset, len))")
        lines.append("    local current_offset = offset")
        lines.append("    local field_values = {}")
        lines.append("")

        for field in protocol.fields:
            lines.append(f"    -- Parse {field.display_name} ({field.name})")

            if field.depends_on_field:
                condition = self._format_lua_condition(field.depends_on_condition)
                lines.append(f"    local dep_val = field_values[\"{field.depends_on_field}\"]")
                lines.append(f"    if dep_val ~= nil and {condition} then")

            if field.is_variable_length and field.length_field:
                lines.append(f"    local {field.name}_len = field_values[\"{field.length_field}\"]")
                lines.append(f"    if {field.name}_len ~= nil and {field.name}_len > 0 then")

                if field.type == FieldType.STRING:
                    lines.append(f"        local field_tvb = tvb(current_offset, {field.name}_len)")
                    lines.append(f"        subtree:add(f.{field.name}, field_tvb)")
                    lines.append(f"        field_values[\"{field.name}\"] = field_tvb:string()")
                else:
                    lines.append(f"        subtree:add(f.{field.name}, tvb(current_offset, {field.name}_len))")
                    get_method = self._get_lua_get_method(field.type)
                    lines.append(f"        field_values[\"{field.name}\"] = tvb(current_offset, {field.name}_len):{get_method}()")

                lines.append(f"        current_offset = current_offset + {field.name}_len")
                lines.append(f"    end")
            else:
                get_method = self._get_lua_get_method(field.type)
                if field.offset >= 0:
                    lines.append(f"    local field_offset = offset + {field.offset}")
                    lines.append(f"    subtree:add(f.{field.name}, tvb(field_offset, {field.length}))")
                    lines.append(f"    field_values[\"{field.name}\"] = tvb(field_offset, {field.length}):{get_method}()")
                    lines.append(f"    if current_offset < field_offset + {field.length} then")
                    lines.append(f"        current_offset = field_offset + {field.length}")
                    lines.append(f"    end")
                else:
                    lines.append(f"    subtree:add(f.{field.name}, tvb(current_offset, {field.length}))")
                    lines.append(f"    field_values[\"{field.name}\"] = tvb(current_offset, {field.length}):{get_method}()")
                    lines.append(f"    current_offset = current_offset + {field.length}")

            if field.depends_on_field:
                lines.append(f"    end")

            lines.append("")

        lines.append("    return current_offset")
        lines.append("end")
        lines.append("")

        lines.append(f"-- Main dissector entry point")
        lines.append(f"function {short_name}.dissector(tvb, pinfo, tree)")
        lines.append(f"    local offset = 0")
        lines.append(f"    local len = tvb:len()")
        lines.append("")

        if protocol.requires_reassembly:
            lines.append(f"    if pinfo.port_type == 2 then  -- TCP")
            lines.append(f"        dissect_{short_name}_tcp(tvb, pinfo, tree, offset, len)")
            lines.append(f"    else")
            lines.append(f"        dissect_{short_name}_pdu(tvb, pinfo, tree, offset, len)")
            lines.append(f"    end")
        else:
            lines.append(f"    dissect_{short_name}_pdu(tvb, pinfo, tree, offset, len)")

        lines.append(f"end")
        lines.append("")

        return "\n".join(lines)

    def _generate_reassembly_function(self, protocol: ProtocolDescription) -> str:
        return self.template_reassembly.format(short_name=protocol.short_name)

    def _generate_heuristic_function(self, protocol: ProtocolDescription) -> str:
        short_name = protocol.short_name
        lines = []

        lines.append(f"-- Heuristic dissector for {protocol.display_name}")
        lines.append(f"function {short_name}.heuristic(tvb, pinfo, tree)")
        lines.append(f"    local total_weight = 0")
        lines.append(f"    local matched_weight = 0")
        lines.append("")

        for rule in protocol.heuristic_rules:
            lines.append(f"    -- Rule: {rule.name} (type: {rule.type.value}, weight: {rule.weight})")
            lines.append(f"    total_weight = total_weight + {rule.weight}")

            if rule.type.value == "fixed_bytes":
                bytes_str = ", ".join([f"0x{b:02x}" for b in rule.expected_bytes])
                lines.append(f"    do")
                lines.append(f"        local matched = true")
                lines.append(f"        local expected = {{{bytes_str}}}")
                lines.append(f"        if tvb:len() >= {rule.offset + len(rule.expected_bytes)} then")
                lines.append(f"            for i = 1, {len(rule.expected_bytes)} do")
                lines.append(f"                if tvb({rule.offset} + i - 1, 1):uint() ~= expected[i] then")
                lines.append(f"                    matched = false")
                lines.append(f"                    break")
                lines.append(f"                end")
                lines.append(f"            end")
                lines.append(f"        else")
                lines.append(f"            matched = false")
                lines.append(f"        end")
                lines.append(f"        if matched then")
                lines.append(f"            matched_weight = matched_weight + {rule.weight}")
                lines.append(f"        end")
                lines.append(f"    end")

            elif rule.type.value == "port_range":
                lines.append(f"    if (pinfo.src_port >= {rule.port_min} and pinfo.src_port <= {rule.port_max}) or")
                lines.append(f"       (pinfo.dst_port >= {rule.port_min} and pinfo.dst_port <= {rule.port_max}) then")
                lines.append(f"        matched_weight = matched_weight + {rule.weight}")
                lines.append(f"    end")

            elif rule.type.value == "entropy_range":
                lines.append(f"    -- Entropy check")
                lines.append(f"    local data_len = tvb:len() - {rule.offset}")
                lines.append(f"    if data_len > 0 then")
                lines.append(f"        matched_weight = matched_weight + {rule.weight * 0.5}")
                lines.append(f"    end")

            lines.append("")

        lines.append(f"    -- Calculate confidence and decide")
        lines.append(f"    if total_weight > 0 and (matched_weight / total_weight) >= 0.7 then")
        lines.append(f"        {short_name}.dissector(tvb, pinfo, tree)")
        lines.append(f"        return true")
        lines.append(f"    end")
        lines.append(f"    return false")
        lines.append(f"end")
        lines.append("")

        return "\n".join(lines)

    def _generate_registration(self, protocol: ProtocolDescription) -> str:
        short_name = protocol.short_name
        lines = []

        lines.append(f"-- Register dissector")
        lines.append(f"local tcp_table = DissectorTable.get(\"tcp.port\")")
        lines.append(f"local udp_table = DissectorTable.get(\"udp.port\")")
        lines.append("")

        if protocol.default_port_tcp:
            lines.append(f"tcp_table:add({protocol.default_port_tcp}, {short_name})")
        if protocol.default_port_udp:
            lines.append(f"udp_table:add({protocol.default_port_udp}, {short_name})")

        lines.append("")
        lines.append(f"-- Register heuristic dissectors")
        lines.append(f"{short_name}:register_heuristic(\"tcp\", {short_name}.heuristic)")
        lines.append(f"{short_name}:register_heuristic(\"udp\", {short_name}.heuristic)")
        lines.append("")

        return "\n".join(lines)

    def _get_lua_field_type(self, field_type: FieldType) -> str:
        type_map = {
            FieldType.UINT8: "uint8",
            FieldType.UINT16: "uint16",
            FieldType.UINT32: "uint32",
            FieldType.UINT64: "uint64",
            FieldType.INT8: "int8",
            FieldType.INT16: "int16",
            FieldType.INT32: "int32",
            FieldType.INT64: "int64",
            FieldType.STRING: "string",
            FieldType.IPV4: "ipv4",
            FieldType.IPV6: "ipv6",
            FieldType.MAC: "ether",
            FieldType.BYTES: "bytes",
            FieldType.VARIABLE: "bytes",
        }
        return type_map.get(field_type, "bytes")

    def _get_lua_base_type(self, field_type: FieldType) -> str:
        if field_type in [FieldType.UINT8, FieldType.UINT16, FieldType.UINT32, FieldType.UINT64,
                          FieldType.INT8, FieldType.INT16, FieldType.INT32, FieldType.INT64]:
            return "DEC"
        return ""

    def _get_lua_get_method(self, field_type: FieldType) -> str:
        type_map = {
            FieldType.UINT8: "uint",
            FieldType.UINT16: "uint",
            FieldType.UINT32: "uint",
            FieldType.UINT64: "uint64",
            FieldType.INT8: "int",
            FieldType.INT16: "int",
            FieldType.INT32: "int",
            FieldType.INT64: "int64",
            FieldType.STRING: "string",
            FieldType.IPV4: "ipv4",
            FieldType.IPV6: "ipv6",
            FieldType.MAC: "ether",
            FieldType.BYTES: "string",
            FieldType.VARIABLE: "string",
        }
        return type_map.get(field_type, "string")

    def _format_lua_condition(self, condition: str) -> str:
        result = condition.replace("==", " == ")
        result = result.replace("!=", " ~= ")
        result = result.replace(">=", " >= ")
        result = result.replace("<=", " <= ")
        result = result.replace(">", " > ")
        result = result.replace("<", " < ")
        return result
