server.port=8081

spring.application.name=station-management

spring.datasource.url=jdbc:h2:mem:stationdb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

spring.mvc.static-path-pattern=/**
spring.web.resources.static-locations=classpath:/static/
